import { Concern } from "./types";

export const mockConcerns: Concern[] = [
  {
    id: "concern-1",
    trackingNumber: "EC-2024-001",
    category: "infrastructure",
    title: "Damaged road in Barangay San Vicente",
    description:
      "The main road in Barangay San Vicente has multiple potholes that make it dangerous for vehicles, especially during rainy season.",
    submitterName: "Juan Dela Cruz",
    submitterEmail: "juan.delacruz@email.com",
    submitterPhone: "+63 917 123 4567",
    location: "Barangay San Vicente, Tarlac City",
    dateSubmitted: "Oct 15, 2024",
    dateSubmittedRaw: new Date("2024-10-15"),
    status: "in-progress",
    priority: "high",
    assignedDepartment: "Engineering Office",
    assignedTo: "Engr. Maria Santos",
    notes: "Inspector dispatched. Estimated repair completion: Nov 5, 2024",
  },
  {
    id: "concern-2",
    trackingNumber: "EC-2024-002",
    category: "public-safety",
    title: "Non-functional streetlights along McArthur Highway",
    description:
      "Several streetlights are not working along McArthur Highway, making the area unsafe at night.",
    submitterName: "Maria Garcia",
    submitterEmail: "maria.garcia@email.com",
    submitterPhone: "+63 918 234 5678",
    location: "McArthur Highway, Tarlac City",
    dateSubmitted: "Oct 18, 2024",
    dateSubmittedRaw: new Date("2024-10-18"),
    status: "pending",
    priority: "medium",
    assignedDepartment: "General Services Office",
    assignedTo: "Pending Assignment",
    notes: "",
  },
  {
    id: "concern-3",
    trackingNumber: "EC-2024-003",
    category: "environment",
    title: "Illegal garbage dumping site",
    description:
      "There is an illegal garbage dumping site near the river in Barangay Maliwalo that needs immediate action.",
    submitterName: "Carlos Mendoza",
    submitterEmail: "carlos.mendoza@email.com",
    submitterPhone: "+63 919 345 6789",
    location: "Barangay Maliwalo, Tarlac City",
    dateSubmitted: "Oct 20, 2024",
    dateSubmittedRaw: new Date("2024-10-20"),
    status: "resolved",
    priority: "high",
    assignedDepartment: "Environment and Natural Resources Office",
    assignedTo: "Mr. Pedro Martinez",
    notes:
      "Site cleaned and monitoring established. Violators identified and warned.",
  },
  {
    id: "concern-4",
    trackingNumber: "EC-2024-004",
    category: "health-social",
    title: "Request for medical assistance program",
    description:
      "Family needs assistance for medical treatment. Requesting support from provincial health office.",
    submitterName: "Ana Torres",
    submitterEmail: "ana.torres@email.com",
    submitterPhone: "+63 920 456 7890",
    location: "Barangay San Nicolas, Tarlac City",
    dateSubmitted: "Oct 22, 2024",
    dateSubmittedRaw: new Date("2024-10-22"),
    status: "in-progress",
    priority: "medium",
    assignedDepartment: "Provincial Health Office",
    assignedTo: "Dr. Liza Rodriguez",
    notes: "Medical assessment scheduled for Oct 28, 2024",
  },
  {
    id: "concern-5",
    trackingNumber: "EC-2024-005",
    category: "education",
    title: "Request for school supplies for public school",
    description:
      "Our public elementary school needs additional school supplies for the upcoming semester.",
    submitterName: "Jose Rizal",
    submitterEmail: "jose.rizal@email.com",
    submitterPhone: "+63 921 567 8901",
    location: "Tarlac Central Elementary School",
    dateSubmitted: "Oct 25, 2024",
    dateSubmittedRaw: new Date("2024-10-25"),
    status: "pending",
    priority: "low",
    assignedDepartment: "Provincial School Board",
    assignedTo: "Pending Assignment",
    notes: "",
  },
  {
    id: "concern-6",
    trackingNumber: "EC-2024-006",
    category: "business-economy",
    title: "Inquiry about business permit renewal process",
    description:
      "Need clarification on the new requirements for business permit renewal.",
    submitterName: "Sofia Alvarez",
    submitterEmail: "sofia.alvarez@email.com",
    submitterPhone: "+63 922 678 9012",
    location: "Tarlac City",
    dateSubmitted: "Oct 27, 2024",
    dateSubmittedRaw: new Date("2024-10-27"),
    status: "resolved",
    priority: "low",
    assignedDepartment: "Business Permits and Licensing Office",
    assignedTo: "Ms. Rosa Santos",
    notes: "Guidance provided. Permit renewal completed.",
  },
  {
    id: "concern-7",
    trackingNumber: "EC-2024-007",
    category: "infrastructure",
    title: "Request for speed bump installation",
    description:
      "Request for speed bump installation near school zone for student safety.",
    submitterName: "Roberto Cruz",
    submitterEmail: "roberto.cruz@email.com",
    submitterPhone: "+63 923 789 0123",
    location: "Near Tarlac High School",
    dateSubmitted: "Oct 28, 2024",
    dateSubmittedRaw: new Date("2024-10-28"),
    status: "pending",
    priority: "high",
    assignedDepartment: "Engineering Office",
    assignedTo: "Pending Assignment",
    notes: "",
  },
  {
    id: "concern-8",
    trackingNumber: "EC-2024-008",
    category: "environment",
    title: "Water pollution concern",
    description:
      "Unusual color and odor in the local water source. Requesting water quality testing.",
    submitterName: "Lourdes Fernandez",
    submitterEmail: "lourdes.fernandez@email.com",
    submitterPhone: "+63 924 890 1234",
    location: "Barangay San Jose, Tarlac City",
    dateSubmitted: "Oct 30, 2024",
    dateSubmittedRaw: new Date("2024-10-30"),
    status: "in-progress",
    priority: "high",
    assignedDepartment: "Environment and Natural Resources Office",
    assignedTo: "Mr. Pedro Martinez",
    notes: "Water sample collected. Awaiting laboratory results.",
  },
];

